### ISSUE TITLE
ADDITIONAL_DEFAULT_PROPERTIES must not be set before here: ro.adb.secure=1

### ISSUE THREAD

**Issue by mfaishalakbar** [halogenOS/android_vendor_xos#3]
Title sums up the problem, Somehow by removing the 

`ADDITIONAL_DEFAULT_PROPERTIES += ro.adb.secure=1 ` 

on config/common.mk resolve the problem.

**Comment by msfjarvis** [comment]
Check Gerrit before opening issues

**Comment by xdevs23** [comment]
Just for reference:
https://review.halogenos.org/#/c/4141/
https://review.halogenos.org/#/c/4142/

**Comment by mfaishalakbar** [comment]
Forgot to check Gerrit first, sorry.
